import {Delete,MailOutline as Mail,Search,Notifications,Cancel,Home,PersonOutline as Person,List,PhotoCamera,PlayCircleOutline,
    TabletMac,Bookmark,Storefront,Settings,ExitToApp,Add,Facebook,Twitter,LinkedIn,
LockOutlined ,ArrowRightAlt,DonutLarge,Chat,MoreVert,AttachFile,
EmojiEmotions,InsertEmoticon,Mic,ShoppingCartOutlined
} from "@material-ui/icons";
    export const Icons={
        Deletes:Delete,
        Email:Mail,
        SearchIcon:Search,
        Notify:Notifications,
        Cancel,
        Home,
        Friends:Person,
        Lists:List,
        Camera:PhotoCamera,
        Video:PlayCircleOutline,
        Apps:TabletMac,
        Collection:Bookmark,
        Market:Storefront,
        Settings,
        Logout:ExitToApp,
        Plus:Add,
        Facebook,
        Twitter,
        LinkedIn,Password:LockOutlined,
        Next:ArrowRightAlt,
        Donut:DonutLarge,
        Chat,More:MoreVert,
        Addfile:AttachFile,
        Emoji:InsertEmoticon,
        Mic,
        Cart:ShoppingCartOutlined,
    };